version: '{branch}.{build}'

# see: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  PROJECT_NAME: php-timecop
  REPORT_EXIT_STATUS: 1
  NO_INTERACTION: 1
  PHP_SDK_DIR: 'C:\projects\php-sdk'
  matrix:
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      PHP_PACKAGE_URL: 'https://secure.php.net/distributions/php-5.4.45.tar.bz2'
#      PHP_SDK_TOOLS_URL: 'http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip'
#      PHP_SDK_DEPS_URL: 'http://windows.php.net/downloads/php-sdk/archives/deps-5.4-vc9-x86_2015-05.7z'
#      VCVARS32_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars32.bat'
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      PHP_PACKAGE_URL: 'https://secure.php.net/distributions/php-5.6.29.tar.bz2'
#      PHP_SDK_TOOLS_URL: 'http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip'
#      PHP_SDK_DEPS_URL: 'http://windows.php.net/downloads/php-sdk/deps-5.6-vc11-x86.7z'
#      VCVARS32_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\vcvars32.bat'
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      PHP_PACKAGE_URL: 'https://secure.php.net/distributions/php-7.1.7.tar.bz2'
#      PHP_SDK_TOOLS_URL: 'http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip'
#      PHP_SDK_DEPS_URL: 'http://windows.php.net/downloads/php-sdk/deps-7.1-vc14-x86.7z'
#      VCVARS32_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\vcvars32.bat'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_PACKAGE_URL: 'https://downloads.php.net/~pollita/php-7.2.0RC6.tar.bz2'
      PHP_SDK_TOOLS_URL: 'https://github.com/Microsoft/php-sdk-binary-tools/archive/php-sdk-2.0.13.zip'
      PHP_SDK_DEPS_URL: ''
      PHP_SDK_VC: 'vc15'		
      VCVARS32_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat'



install:
- cmd: >-
    set PROJECT_DIR=C:\projects\%PROJECT_NAME%

    set TEST_PHP_EXECUTABLE=%PROJECT_DIR%\bin\php.exe

    for /f %%F in ("%PHP_PACKAGE_URL%") do set PHP_PACKAGE_FILENAME=%%~nxF

    set PHP_SRC_DIR=C:\projects\%PHP_PACKAGE_FILENAME:.tar.bz2=%

    for /f %%F in ("%PHP_SDK_TOOLS_URL%") do set PHP_SDK_TOOLS_FILENAME=%%~nxF

    set PHP_SDK_TOOLS_SUBDIR=php-sdk-binary-tools-%PHP_SDK_TOOLS_FILENAME:.zip=%

    for /f %%F in ("%PHP_SDK_DEPS_URL%") do set PHP_SDK_DEPS_FILENAME=%%~nxF

    set TEST_PHP_EXECUTABLE=%PROJECT_DIR%\bin\php.exe

    choco feature enable -n=allowGlobalConfirmation

    cinst wget

    mkdir %PROJECT_DIR%\bin

build_script:
- cmd: >-
    echo %APPVEYOR_BUILD_WORKER_IMAGE%

    echo %PROJECT_DIR%

    echo %TEST_PHP_EXECUTABLE%

    "%VCVARS32_PATH%"

    wget %PHP_PACKAGE_URL%

    7z x -so %PHP_PACKAGE_FILENAME% | 7z x -si -ttar -oC:\projects\

    wget %PHP_SDK_TOOLS_URL%

    7z x -y  %PHP_SDK_TOOLS_FILENAME% -o%PHP_SDK_DIR%

    if exist %PHP_SDK_DIR%\%PHP_SDK_TOOLS_SUBDIR% ( cd %PHP_SDK_DIR%\%PHP_SDK_TOOLS_SUBDIR% ) else ( cd %PHP_SDK_DIR% )

    dir

    mkdir %PHP_SRC_DIR%\ext\%PROJECT_NAME%

    xcopy %PROJECT_DIR% %PHP_SRC_DIR%\ext\%PROJECT_NAME% /s /e /y

    dir %PHP_SRC_DIR%

    cd %PHP_SRC_DIR%

    %PHP_SDK_DIR%\%PHP_SDK_TOOLS_SUBDIR%\bin\phpsdk_deps.bat -u

    buildconf.bat

    rem "Build failed with '--enable-zip' on PHP 7.2.0 beta1"

    configure.bat --disable-all --enable-phar --enable-json --enable-hash --enable-ctype --enable-filter --enable-tokenizer --with-iconv --with-openssl --with-dom --with-libxml --enable-zip --enable-timecop=shared --enable-cli --enable-zts --with-config-file-scan-dir=%PROJECT_DIR%\bin\modules.d --with-prefix=%PROJECT_DIR%\bin --with-php-build=deps

    nmake

    nmake install

    copy php.ini-development %PROJECT_DIR%\bin\php.ini

    mkdir %PROJECT_DIR%\bin\modules.d

    echo extension=php_timecop.dll >> %PROJECT_DIR%\bin\modules.d\php.ini

test_script:
- cmd: >-
    echo %PROJECT_DIR%

    echo %TEST_PHP_EXECUTABLE%

    cd %PROJECT_DIR%

    if exist bin dir bin

    if exist bin\ext dir bin\ext

    if exist bin\modules.d dir bin\modules.d

    "%TEST_PHP_EXECUTABLE%" %PHP_SRC_DIR%\run-tests.php --show-diff

    exit /b %errorlevel%

# see: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
